-- Generated by scripts/build-content-sql.mjs from seed/starter-content.json. Do not edit by hand.

INSERT INTO news (title, body, snippet, source_url, source_name, published_at, sort_order)
SELECT '6.4.26 International Eventing Results.', 'Another huge entry at Thoresby gives Irish breeding a serious showcase, with more than 50% of Top 10 Places taken in the CCIs.
USA is now in full swing with lots of Irish on Show.

See below the up-to-date results for this week – unverified results will be added to next week’s results', 'Another huge entry at Thoresby gives Irish breeding a serious showcase, with more than 50% of Top 10 Places taken in the CCIs. USA is now in full swing with lots of Irish on Show. See below the up-to-date results for…', '', '', '2026-04-06 12:00:00', 1
WHERE NOT EXISTS (SELECT 1 FROM news WHERE title = '6.4.26 International Eventing Results.');

INSERT INTO news (title, body, snippet, source_url, source_name, published_at, sort_order)
SELECT 'Irish Sport Horses win 5 classes including 2 CCIs at the GMH Festival', 'Martin Crowley’s Crossfield Lass breeds two Top 10 Places at Open Preliminary. OBOS Quality has 7 mentions but only one as a Dam’s Sire and TIH get 17 mentions.

Rocking Horse Winter Horse trials (USA) 14th – 16th February 2025
Advanced Test A
1st Luska Candy Clover [ISH][was HSH Luska Legend] – 2013 gelding by Sligo Candy Boy [ISH] out of Miss Demeanor [ISH] by White Clover (ISH)[TIH]. Breeder: Amie Sterling (Tipperary). Rider: Jack Curtis (USA) 32., 0, 15.6 = 47.7

2nd Lissavorra Quality (ISH) – 2016 mare by OBOS Quality 004 (OLD) out of Soolmoy Lucy (ISH) by Lux Z (HANN). Breeder: Patrick McLoughney. Rider: Elisa Wallace (USA) 30.5, 4, 42.4 = 76.9.

Only 3 finished.

Advanced Test B
2nd Cooley Candyman [ISH][was Tempo Candy Hill] – 2013 gelding by Sligo Candy Boy [ISH] out of Dashing Hill [ISH] by FlameHill [ISH]. Breeder: Thomas Anthony Jones (Sligo). Rider: Bruce Davidson Jnr (USA) 28.0, 4, 13.6 = 45.6

3rd SSH Playboy (unk) – 2012 gelding OIO by Cit Cat (HOLST) out of Stomeyford Black Pearl (unk). Breeder: Ennisnag Stud. Rider: Julie Wolfert (USA) 35.5, 0, 11.2 = 46.7

4th SBT Barolo (ISH)[was CSF High on Life] – 2010 gelding by Loughehoe Guy (ISH)[TIH] out of Tentore Flight (AES)(P) by Carrolls Flight (AES). Breeder: Brian Connolly (Galway). Rider: Robin Walker (USA) 27.1, 4, 20.8 = 51.9

7th Cooley Baltic Sea (ISH)[was Cooley Pot of Gold & Annaghmore Baltic Sea] – 2014 gelding by  Baltic VDL (KWPN) out of HHS Cheerio (ISH) by Harlequin du Carel (SF). Breeder: Judy Tobin & Aoife Healion. Rider: Arielle Aharoni (USA) 37.1, 4, 12.8 = 53.9

8th Trinity ThankQ (ISH)[was Trinity Thank Q] – 2016 gelding by Beach Ball (ISH) out of Ballyderowen Clover (ISH). Breeder: Brendan Cave. Rider: Lisa Marie Fergusson (CAN) 38.0, 4, 43.6 = 85.6.

Open Intermediate A
5th Rock Jennings (ISH)[TIH] – 2016 gelding by Tajraasi (TB) out of Miss Goatenbridge (ISH)[TIH] by Crosstown Dancer (ID). Breeder: James Carey. Rider: Micheal Nolan (IRL) 34.3, 0, 14.0 = 48.3

7th Rosconnell Alto (ISH) – 2015 gelding by Tabasco Van Erpekom (BWP) out of All Clover (ISH) by Cavalier Clover Lad (ISH). Breeder: Patrick Lacey. Rider: Kiersten Miller (USA) 35.7, 4, 13.2 = 52.9.

Open Intermediate B
3rd Gortglass Lupin (ISH) – 2017 gelding by Luidam (KWPN) out of Gortglas Skye (ISH)[TIH] by Master Imp (TB). Breeder: Sian Carson Ball. Rider: Gabby Dickerson (USA) 37.5, 4, 0.4 = 41.9

6th Rock Phantom (ISH)[TIH][was Fernhill Rock Phantom] – 2011 gelding by Sprit House (TB) out of Ballycroy Rose (ID) by Clonakilty Hero (ID). Breeder: Maura O’Malley (Mayo). Rider: Sara Kozumplik (USA) 30.7, 12, 6.4 = 49.1

8th Ratheoin Quality Imp (ISH) – 2017 gelding by OBOS Quality 004 (OLD) out of Coonogues Dawn (ISH) by Master Imp (TB). Breeder: Sean Barron. Rider: Lisa Marie Fergusson (CAN) 37.3, 0, 17.4 = 55.7.

Intermediate Rider
5th Fernhill Focus Maxi (ISH)[was BSI Focus Maximus] – 2013 gelding by Candillo Z (HOLST) out of Stay Focused (ISH) by ARD VDL Douglas (KWPN). Breeder: Michael Buckley (Waterford). Rider: Jake Tessler (USA) 40.9, 4, 1.6 = 46.5.

Open Preliminary A
2nd Fernhill Quite Frankly (ISH) – 2015 gelding by OBOS Quality 004 (OLD) out of Rusheen Lux (ISH) by Lux Z (HANN). Breeder: Gerard Grace. Rider: Rebecca Brown (USA) 31.1, 0, 0.4 = 31.5

10th Kilcannon Kandy Kid [ISH] – 2013 gelding by Sligo Candy Boy [ISH] out of Charlestown Daisy (ISH)[TIH] by Cruise On (ISH)[TIH]. Breeder: Patrick J Wall (Mayo). Rider: Kelty O’Donoghue (USA) 35.9, 0, 24.0 = 59.9.

Open Preliminary B
1st Cooley Starship (ISH) – 2015 gelding by Cobra (HOLST) out of Simona (SWB) by Leuthen 1 (HOLST). Breeder: Tom Moloney (Kilkenny). Rider: Isabelle Bosley (USA) 29.6, 0, 0.0 = 29.6

8th Ballygriffin Crossfield Cara (ISH) – 2017 mare by OBOS Quality 004 (OLD) out of Crossfield Lass (ISH) by High Roller (ISH). Breeder: Martin Crowley. Rider: Joe Meyer (NZL) 32.1, 0, 23.6 = 55.7

9th Woodview Diamond Star (ISH)[was Monbeg Cinnamon] – 2016 gelding by Cobra (HOLST) out of Ballycreen Nanoschka (ISH)[TIH] by Nearly A Nose (TB). Breeder: Gerard Ryan. Rider: Kelsey Hoiness (USA) 31.4, 13.2, 12.4 = 57.0

10th Cooley Quickfire (ISH)[was Veni Vidi Vici] – 2017 gelding by Womanizer (KWPN) out of Air Cruise (ISH) by Cruising (ISH)[TIH]. Breeder: Diana H Warrington. Rider: Michael Nolan (IRL) 33.0, 8, 17.6 = 58.6.

Open Preliminary One Day A
5th MT Luxaan (ISH) – 2018 mare by Cazaan (HOLST) out of Lux So Easy (ISH) by Lux Z (HANN). Breeder: Gareth Carlisle. Rider: Cassie Sanger (USA) 25.2, 0, 14.0 = 39.2

6th Dondante (ISH) – [was Cooley All Air] – 2010 gelding by Pacino (BWP) out of Muckno Clover [ISH] by Euro Clover [ISH]. Breeder: Francis Brennan (Monaghan). Rider: Meg Pellegrini (USA) 34.1, 0.4, 16.0 = 50.5

7th Cooley Northern Mist (ISH) – 2010 gelding by Cobra (HOLST) out of Neat Moonlight Clover (ISH) by Countach (OLD). Breeder: Nicola Tang (Derry). Rider: Cassie Sanger (USA) 28.0, 0, 22.8 = 50.8

8th Fernhill Let’s Face It (ISH) – 2011 gelding by Irko (WESTF) out of Warrenstown Josie (ISH) by Cavalier Royale (HOLST). Breeder: Cliodhna Gleeson (Tipperary). Rider: Ainsley Slicker (USA) 35.7, 12, 5.2 = 52.9

9th Always Cooley (unk) – 2011 mare OIO by Ramiro B. Rider: Audrey Ogan (USA) 35.0, 0, 18.4 = 53.4.

Open Preliminary One Day B
1st Boleybawn Oliva (ISH) – 2018 mare by Jorado (KWPN) out of C-Jumps (SCSL) by Cicero Z Van Parmal (BWP). Breeder: Boleybawn Horses Ltd. Rider: Hallie Coon (USA) 28.0, 0, 0.0 = 28.0.

Preliminary Horse
3rd MHE Briarhill Excel Star Cassondra (ISH)[was Briarhill Chacoa K, Briarhill Star Cass] – 2019 mare by Kings Cornet (ISH) out of Briarhill Temple (ISH) by Chacoa (HOLST). Breeder: Anne Coyne. Rider: Morgan Houberg (USA) 34.6, 12, 0.0 = 46.6.

Preliminary Rider
10th Ballygriffin Chacoa Power (ISH)[was Crossfield Sheeco] – 2014 mare by Chacoa (HOLST) out of Crossfield Lass (ISH) by High Roller (ISH). Breeder: Martin Crowley. Rider: Danielle Platt (USA) 43.0, 0, 8.0 = 51.0.

Open Modified A
3rd Water Mill Smooth (ISH)[TIH] – 2014 gelding by Watermill Swatch (TB) out of My Smooth Damond (ISH)[TIH] by Diamond Lad (ID).  Breeder: Alan Connaughton. Rider: Kelsey Seidel (USA) 29.5, 0, 0.0 = 29.5

4th Rock Island (ISH)[TIH] – 2017 gelding by Island Commander (TB) out of Coolcorren Gypsey (ISH)[TIH] by Coolcorran Cool Diamond (ISH). Breeder: Michael Byrne. Rider: Robin Walker (USA) 27.6, 0, 2.0 = 29.6

5th Hillside Diamond Lad (ISH)[TIH] – 2017 gelding by Lionwood Kinsales Lad (ID) out of Wedding Day (TB) by With Approval (TB). Breeder: Sarah Cleary. Rider: Liz Lund (USA) 29.8, 0, 0.0 = 29.8.

Open Modified One Day A
10th Crugraff (ISH) – 2010 gelding by Kroongraaf (KWPN) out of Tullibards Pretty Young Thing [ISH} by Cruising (ISH)[TIH]. Breeder: John Higgins (Derry). Rider: Barbie Violi (USA) 34.1, 0, 22.8 = 56.9.

Open Modified One Day B
4th Fernhill Quality Vision (ISH)[was Quality Vision] – 2015 gelding by OBOS Quality 004 (OLD) out of Lady Carla (ISH) by Welcome Flagmount (ID). Breeder: Sinead Murphy. Rider: Stephanie Jackson (USA) 33.6, 0, 0.0 = 33.6

5th HTF Cosmic Cooley (ISH)[was Cookstown Sparrow] – 2019 mare by Coupe de Coeur (HOLST) out of Gortglass Sparrow (ISH)[TIH] by Ashfield Bobby Sparrow (CP). Breeder: Donal Callery. Rider: Chris Talley (USA) 33.8, 0, 0.0 = 33.8

7th Fernhill 767 (ISH)[was KEC Paqx] – 2017 gelding by OBOS Quality 004 (OLD) out of Killerick Diamond (ISH) by Glidawn Diamond (ID). Breeder: Oonagh Kennedy. Rider: Amelia Ebhardt (USA) 33.6, 4, 0.0 = 37.6.

Ram Trap Horse Park Horse Trials (USA) 14th – 16th February 2025
Open Intermediate
3rd GHS Calexico (ISH) – 2015 mare by Van Gogh (KWPN) out of Penhaligon Cairo (AES) by Cavalier Royale (HOLST). Breeder: Leanne Marshall. Rider: Marc Grandia (USA) 30.2, 0.4, 8.4 = 39.0

4th Cooley Mr. Murphy (ISH) – 2013 gelding by Kroongraaf (KWPN) out of Ballinabarney Highlight (ISH) by OBOS Quality 004 (OLD). Breeder: John Burke (Galway). Rider: Sabrina Glaser (CAN) 33.4, 1.6, 6.8 = 41.8

6th Balladeer Kilbrickens Lad (ISH) – 2015 gelding by A. Umonia 60 (KWPN) out of Aubane Girl (ISH) by Silvano (KWPN). Breeder: Sarah Phelan. Rider: Tommy Greengard (USA) 26.0, 0, 20.8 = 46.8.

Preliminary Rider
1st Cooley Neptune (ISH)[was Annaghmore Rebel Beach] – 2015 gelding by Beach Ball (ISH) out of Annaghmore Temptress (KWPN) by Iroko (WESTF). Breeder: John Maguire. Rider: Jullian Mader (USA) 29.7, 4, 0.0 = 33.7.

Open Modified
8th Carel Cruiser (ISH) – 2016 gelding by Numero Cruise (ISH) out of Katelyns Carel (ISH) by Harlequin du Carel (SF). Breeder: Martin Reilly. Rider: Lauren Henry (USA) 34.8, 4, 5.6 = 44.4.

Jumping Branch Farm Horse Trials (USA) 15th – 16th February 2025
Open Preliminary
1st Curraghraigue Clear Future (ISH) – 2015 gelding by Womanizer (KWPN) out of Curraghgraigue Coevers Z [ISH] by Coevers Diamond Boy [ISH]. Breeder: Baden Powell (Tipperary). Rider: Boyd Martin (USA) 24.5, 0, 0.0 = 24.5

8th Cooley Constellation (ISH)[was GH Cooley] – 2017 gelding by Tolan R (KWPN) out of Beachnut (ISH) by Beach Ball (ISH). Breeder: Jennifer French. Rider: Brooke Burchianti (USA) 41.8, 4, 16.0 = 61.8.

These results have been provided to Horse Sport Ireland by Charlie Ripman,

These results are funded by Horse Sport Ireland.', 'Martin Crowley’s Crossfield Lass breeds two Top 10 Places at Open Preliminary. OBOS Quality has 7 mentions but only one as a Dam’s Sire and TIH get 17 mentions. Rocking Horse Winter Horse trials (USA) 14th – 16th…', 'https://www.horsesportireland.ie/irish-sport-horses-win-5-classes-including-2-ccis-at-the-gmh-festival/', 'Horse Sport Ireland', '2025-02-17 12:00:00', 2
WHERE NOT EXISTS (SELECT 1 FROM news WHERE title = 'Irish Sport Horses win 5 classes including 2 CCIs at the GMH Festival');

INSERT INTO news (title, body, snippet, source_url, source_name, published_at, sort_order)
SELECT 'Proof, if it were needed, why Traditionally bred Irish mares are so important to the export market.', 'Proof, if it were needed, why Traditionally bred Irish mares are so important to the export market.
Looking at the eventing results for the week of 16.5 22 there were 49 classes in the UK and just 11 in the USA. Because not all classes have 10 finishers there were 480 T10Ps available in the UK and 99 in the USA. In the UK 38.1% were taken by Irish bred horses. A huge percentage when you remember that there are not only the homebred eventers but many Dutch and other continental imports competing at all levels. In the USA (with a very small number of classes) 23.2% were ISH. Considering the cost of shipping and the large number of ex racehorses used in the lower classes it is a credit to the Irish breeders that Ireland is the ‘go to’ stock for eventers in the USA.
Turning now at the horses who took a T10Place in the UK, 14.2% were themselves TIH of the 183 Irish bred horses (21.7% in the USA), 10.9% had TIH sires (4.3% in the USA) 12.5% had TIH Dam’s sires (26.1% in the USA) but most impressively 30% had TIH dams (30,4% in the USA). Because the vast majority of breeding mares in Ireland are plain ISH (either because they or in their parentage, there is lack of registered breeding or there are Warmblood genes within that pedigree) it is an impressive case of punching above their weight for those few TIH breeding mares left in Ireland.
If those responsible for the Irish Sport Horse (be they those that set out the future breeding plans or those that breed these valuable mares or the producers and sellers) don’t retain these TIH mares in Ireland, then the Traditional Irish Horse will become extinct.

Thank you Charlie Ripman as always for all the great statistics. We are very proud and determined to retain our traditional mares in our breeding programme. These high blood mares going back to old Irish blood lines are without doubt unique. We feel very strongly that they will present standout opportunities moving forward in a marketplace that will become so muddied by similarity.
Traditional Irish Horse Association #irishheritage #irishculture #irishhorse', 'Proof, if it were needed, why Traditionally bred Irish mares are so important to the export market. Looking at the eventing results for the week of 16.5 22 there were 49 classes in the UK and just 11 in the USA. Because…', '', 'Charlie Ripman on Facebook', '2022-05-25 12:00:00', 3
WHERE NOT EXISTS (SELECT 1 FROM news WHERE title = 'Proof, if it were needed, why Traditionally bred Irish mares are so important to the export market.');

INSERT INTO news (title, body, snippet, source_url, source_name, published_at, sort_order)
SELECT 'I accept that this is early on in the research but I am looking at the horses that achieved a Top 10 Place in the UK in 2021 and were born in 2004 and later.', 'I accept that this is early on in the research but I am looking at the horses that achieved a Top 10 Place in the UK in 2021 and were born in 2004 and later. There are 4,525 in total which includes all T10 Placed Irish bred horses.
Of the 376 with names beginning with A and B
77.7% had some TIH in their recent breeding or were themselves TIH.
22.9% were pure TIH.
5.8% had TIH Sires.
34.5% had TIH Dams.
10% had Dam’s Sires who were TIH.
This shows how influential TIH is in the breeding of Event horses aimed at export.

Irish Draught Horse Society Limited. Northern Ireland
January 20, 2022
Charlie Ripman continues to produce fantastic information highlighting the value of the Traditional Irish Horse (TIH) which as you will be aware can only have Irish Draught, Tb and / or Connemara blood in the pedigree.', 'I accept that this is early on in the research but I am looking at the horses that achieved a Top 10 Place in the UK in 2021 and were born in 2004 and later. There are 4,525 in total which includes all T10 Placed Irish…', '', 'Charlie Ripman on Facebook', '2022-01-20 12:00:00', 4
WHERE NOT EXISTS (SELECT 1 FROM news WHERE title = 'I accept that this is early on in the research but I am looking at the horses that achieved a Top 10 Place in the UK in 2021 and were born in 2004 and later.');

INSERT INTO link_cards (title, url, teaser, source_name, card_date, sort_order)
SELECT 'Irish Sport Horses win 5 classes including 2 CCIs at the GMH Festival', 'https://www.horsesportireland.ie/irish-sport-horses-win-5-classes-including-2-ccis-at-the-gmh-festival/', '', 'Horse Sport Ireland', '', 1
WHERE NOT EXISTS (SELECT 1 FROM link_cards WHERE title = 'Irish Sport Horses win 5 classes including 2 CCIs at the GMH Festival');

INSERT INTO link_cards (title, url, teaser, source_name, card_date, sort_order)
SELECT 'Irish Sport Horses doing best when x-country is toughest', 'https://www.horsesportireland.ie/irish-sport-horses-doing-best-when-x-country-is-toughest/', '', 'Horse Sport Ireland', '', 2
WHERE NOT EXISTS (SELECT 1 FROM link_cards WHERE title = 'Irish Sport Horses doing best when x-country is toughest');

INSERT INTO link_cards (title, url, teaser, source_name, card_date, sort_order)
SELECT 'HAVE YOUR SAY COLUMN: Protect our TIH heritage', 'https://www.theirishfield.ie/have-your-say-column-protect-our-tih-heritage-630032', 'Charlie Ripman gives his personal take on the influence of Traditional Irish Horses in eventing to date this year', 'The Irish Field', '', 3
WHERE NOT EXISTS (SELECT 1 FROM link_cards WHERE title = 'HAVE YOUR SAY COLUMN: Protect our TIH heritage');
