-- IrishBredShowjumpingResults (IBSR) site database: the same tables as IBER (from migrations/0001 to
-- 0021_canadian_event_only_its_own_result.sql), empty. None of IBER's results, articles, ads or subscribers are copied.
-- Generated by scripts/build-ibsr-site-schema.mjs. Edit IBER's migrations, then run it again.

CREATE TABLE batches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  label TEXT NOT NULL DEFAULT '',
  row_count INTEGER NOT NULL DEFAULT 0,
  unverified_count INTEGER NOT NULL DEFAULT 0
, published INTEGER NOT NULL DEFAULT 1);
CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  date_text TEXT NOT NULL DEFAULT '',
  start_date TEXT NOT NULL DEFAULT '',   -- YYYY-MM-DD, used for sorting
  country TEXT NOT NULL DEFAULT '',
  season INTEGER NOT NULL
, end_date TEXT NOT NULL DEFAULT '', source_notes TEXT NOT NULL DEFAULT '', article_url TEXT NOT NULL DEFAULT '', article_date TEXT NOT NULL DEFAULT '');
CREATE INDEX idx_events_season ON events(season, start_date);
CREATE UNIQUE INDEX idx_events_key ON events(name, start_date, country);
CREATE TABLE classes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_classes_key ON classes(event_id, name);
CREATE TABLE placings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
  batch_id INTEGER REFERENCES batches(id) ON DELETE CASCADE,
  position INTEGER,
  horse_name TEXT NOT NULL DEFAULT '',
  former_name TEXT NOT NULL DEFAULT '',
  breed TEXT NOT NULL DEFAULT '',
  foaled INTEGER,
  sex TEXT NOT NULL DEFAULT '',
  sire TEXT NOT NULL DEFAULT '',
  dam TEXT NOT NULL DEFAULT '',
  dam_sire TEXT NOT NULL DEFAULT '',
  breeder TEXT NOT NULL DEFAULT '',
  dressage TEXT NOT NULL DEFAULT '',
  show_jumping TEXT NOT NULL DEFAULT '',
  cross_country TEXT NOT NULL DEFAULT '',
  score REAL,
  verified INTEGER NOT NULL DEFAULT 1
, result_id INTEGER REFERENCES results(id));
CREATE INDEX idx_placings_class ON placings(class_id, position);
CREATE INDEX idx_placings_batch ON placings(batch_id);
CREATE INDEX idx_placings_name ON placings(horse_name COLLATE NOCASE);
CREATE INDEX idx_placings_verified ON placings(verified);
CREATE VIRTUAL TABLE placings_fts USING fts5(
  horse_name, former_name, sire, dam, dam_sire, breeder,
  content='placings', content_rowid='id',
  tokenize = "unicode61 remove_diacritics 2"
);
CREATE TRIGGER placings_ai AFTER INSERT ON placings BEGIN
  INSERT INTO placings_fts(rowid, horse_name, former_name, sire, dam, dam_sire, breeder)
  VALUES (new.id, new.horse_name, new.former_name, new.sire, new.dam, new.dam_sire, new.breeder);
END;
CREATE TRIGGER placings_ad AFTER DELETE ON placings BEGIN
  INSERT INTO placings_fts(placings_fts, rowid, horse_name, former_name, sire, dam, dam_sire, breeder)
  VALUES ('delete', old.id, old.horse_name, old.former_name, old.sire, old.dam, old.dam_sire, old.breeder);
END;
CREATE TRIGGER placings_au AFTER UPDATE ON placings BEGIN
  INSERT INTO placings_fts(placings_fts, rowid, horse_name, former_name, sire, dam, dam_sire, breeder)
  VALUES ('delete', old.id, old.horse_name, old.former_name, old.sire, old.dam, old.dam_sire, old.breeder);
  INSERT INTO placings_fts(rowid, horse_name, former_name, sire, dam, dam_sire, breeder)
  VALUES (new.id, new.horse_name, new.former_name, new.sire, new.dam, new.dam_sire, new.breeder);
END;
CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  snippet TEXT NOT NULL DEFAULT '',
  image_key TEXT,
  published_at TEXT NOT NULL DEFAULT (datetime('now'))
, sort_order INTEGER NOT NULL DEFAULT 0, source_url TEXT NOT NULL DEFAULT '', source_name TEXT NOT NULL DEFAULT '');
CREATE INDEX idx_news_published ON news(published_at DESC);
CREATE TABLE ads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tier TEXT NOT NULL CHECK (tier IN ('large', 'small')),
  name TEXT NOT NULL,
  link TEXT NOT NULL DEFAULT '',
  image_key TEXT,
  ends_on TEXT,                          -- YYYY-MM-DD; the ad stops showing after this day
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, slot INTEGER, starts_on TEXT, fit TEXT NOT NULL DEFAULT 'cover', focus TEXT NOT NULL DEFAULT 'center', orig_key TEXT, crop TEXT NOT NULL DEFAULT '', bg TEXT NOT NULL DEFAULT '#ffffff', phone_key TEXT, phone_crop TEXT NOT NULL DEFAULT '', placement TEXT);
CREATE TABLE comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scope TEXT NOT NULL CHECK (scope IN ('results', 'news')),
  name TEXT NOT NULL,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, spam_check TEXT NOT NULL DEFAULT 'passed');
CREATE INDEX idx_comments_status ON comments(status, scope, created_at);
CREATE TABLE corrections (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_text TEXT NOT NULL,
  message TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE subscribers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE COLLATE NOCASE,
  confirmed INTEGER NOT NULL DEFAULT 0,
  token TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE enquiries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  business TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  interest TEXT NOT NULL DEFAULT 'unsure',
  message TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE sires (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  name_normalised TEXT NOT NULL UNIQUE,
  breed_code TEXT NOT NULL DEFAULT '',
  tih_flag INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, birth_year INTEGER, ped_sire TEXT NOT NULL DEFAULT '', ped_dam TEXT NOT NULL DEFAULT '', ped_dam_sire TEXT NOT NULL DEFAULT '', ped_breeder TEXT NOT NULL DEFAULT '');
CREATE TABLE dams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  name_normalised TEXT NOT NULL,
  breed_code TEXT NOT NULL DEFAULT '',
  tih_flag INTEGER NOT NULL DEFAULT 0,
  sire_id INTEGER REFERENCES sires(id),           -- the dam's own sire (the horse's dam sire)
  sire_key INTEGER GENERATED ALWAYS AS (IFNULL(sire_id, 0)) STORED,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX ux_dams_identity ON dams(name_normalised, sire_key);
CREATE TABLE breeders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  name_normalised TEXT NOT NULL,
  county TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX ux_breeders_identity ON breeders(name_normalised, county);
CREATE TABLE horses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  name_normalised TEXT NOT NULL,
  birth_year INTEGER,
  sex TEXT NOT NULL DEFAULT '',
  breed_code TEXT NOT NULL DEFAULT '',
  tih_flag INTEGER NOT NULL DEFAULT 0,
  sire_id INTEGER REFERENCES sires(id),
  dam_id INTEGER REFERENCES dams(id),
  damsire_id INTEGER REFERENCES sires(id),
  breeder_id INTEGER REFERENCES breeders(id),
  notes TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  -- One horse = name + year of birth + sire + dam. Missing values count as 0 so they still match.
  identity_key TEXT GENERATED ALWAYS AS (
    name_normalised || '|' || IFNULL(birth_year, 0) || '|' || IFNULL(sire_id, 0) || '|' || IFNULL(dam_id, 0)
  ) STORED
, breeding_source TEXT NOT NULL DEFAULT '', breeding_updated_at TEXT);
CREATE UNIQUE INDEX ux_horses_identity ON horses(identity_key);
CREATE TABLE horse_aliases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  horse_id INTEGER NOT NULL REFERENCES horses(id) ON DELETE CASCADE,
  former_name TEXT NOT NULL,
  former_name_normalised TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_horse_aliases ON horse_aliases(horse_id, former_name_normalised);
CREATE TABLE results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  horse_id INTEGER NOT NULL REFERENCES horses(id),
  rider_name TEXT NOT NULL DEFAULT '',
  rider_country TEXT NOT NULL DEFAULT '',
  class_name TEXT NOT NULL,
  placing INTEGER,
  dressage TEXT NOT NULL DEFAULT '',
  xc_jumping TEXT NOT NULL DEFAULT '',
  show_jumping TEXT NOT NULL DEFAULT '',
  total REAL,
  week_label TEXT NOT NULL DEFAULT '',
  verified INTEGER NOT NULL DEFAULT 1,
  batch_id INTEGER REFERENCES batches(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, article_url TEXT NOT NULL DEFAULT '', article_date TEXT NOT NULL DEFAULT '', raw_line TEXT NOT NULL DEFAULT '', parse_ok INTEGER NOT NULL DEFAULT 1);
CREATE UNIQUE INDEX ux_results_identity ON results(event_id, class_name, horse_id);
CREATE INDEX idx_horses_name ON horses(name_normalised);
CREATE INDEX idx_horses_sire ON horses(sire_id);
CREATE INDEX idx_horses_dam ON horses(dam_id);
CREATE INDEX idx_horses_damsire ON horses(damsire_id);
CREATE INDEX idx_horses_breeder ON horses(breeder_id);
CREATE INDEX idx_dams_sire ON dams(sire_id);
CREATE INDEX idx_aliases_name ON horse_aliases(former_name_normalised);
CREATE INDEX idx_results_horse ON results(horse_id);
CREATE INDEX idx_results_event ON results(event_id);
CREATE INDEX idx_results_batch ON results(batch_id);
CREATE UNIQUE INDEX ux_placings_class_horse ON placings(class_id, lower(horse_name));
CREATE TABLE name_matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('sire', 'dam', 'breeder', 'horse')),
  match_key TEXT NOT NULL,
  target_id INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE UNIQUE INDEX ux_name_matches ON name_matches(kind, match_key);
CREATE INDEX idx_news_order ON news(sort_order, published_at DESC);
CREATE TABLE link_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  teaser TEXT NOT NULL DEFAULT '',
  source_name TEXT NOT NULL DEFAULT '',
  image_key TEXT,
  card_date TEXT NOT NULL DEFAULT '',          -- YYYY-MM-DD, shown on the card
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_link_cards_order ON link_cards(sort_order, card_date DESC);
CREATE INDEX idx_results_parse_ok ON results(parse_ok);
CREATE INDEX idx_ads_placement ON ads(placement);
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
CREATE TABLE stallions (
  slot INTEGER PRIMARY KEY CHECK (slot BETWEEN 1 AND 6),
  name TEXT NOT NULL DEFAULT '',
  sire_names TEXT NOT NULL DEFAULT '',
  blurb TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  image_key TEXT,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE analytics (
  day TEXT NOT NULL,              -- YYYY-MM-DD (UTC)
  kind TEXT NOT NULL,             -- visit | view | ad | link
  key TEXT NOT NULL DEFAULT '',   -- view: the page; ad: advert id|space; link: link card id
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, kind, key)
);

INSERT OR IGNORE INTO settings (key, value) VALUES ('ad_price_side', '600');
INSERT OR IGNORE INTO settings (key, value) VALUES ('ad_price_top', '3000');
