// Builds seed/sample.sql from the approved mockup's sample week, run through the real parser.
// Riders in the mockup data are dropped by the parser, as they are for Charlie's files.
//   node scripts/build-seed.mjs
import { writeFileSync } from 'node:fs';
import { mockupData, horsesToText } from './mockup-data.mjs';
import { parseResults } from '../lib/parser.js';

const q = v => (v === null || v === undefined || v === '' ? (v === '' ? "''" : 'NULL') : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const { horses, articles } = mockupData();
const { rows } = parseResults(horsesToText(horses), { defaultYear: 2026 });

const out = ['-- Sample data from reference/irishbredeventers-mockup-v2.html. Generated by scripts/build-seed.mjs.', ''];
out.push(`INSERT INTO batches (id, created_at, label, row_count, unverified_count) VALUES (1, '2026-04-06 08:00:00', 'Sample week (from the mockup)', ${rows.length}, ${rows.filter(r => !r.verified).length});`);

const events = new Map(), classes = new Map();
for (const r of rows) {
  const ek = `${r.event_name}|${r.start_date}|${r.country}`;
  if (!events.has(ek)) {
    events.set(ek, events.size + 1);
    out.push(`INSERT INTO events (id, name, date_text, start_date, country, season) VALUES (${events.size}, ${q(r.event_name)}, ${q(r.event_date_text)}, ${q(r.start_date)}, ${q(r.country)}, ${r.season});`);
  }
  const ck = `${events.get(ek)}|${r.class_name}`;
  if (!classes.has(ck)) {
    classes.set(ck, classes.size + 1);
    out.push(`INSERT INTO classes (id, event_id, name) VALUES (${classes.size}, ${events.get(ek)}, ${q(r.class_name)});`);
  }
  out.push(`INSERT INTO placings (class_id, batch_id, position, horse_name, former_name, breed, foaled, sex, sire, dam, dam_sire, breeder, dressage, show_jumping, cross_country, score, verified) VALUES (${[
    classes.get(ck), 1, r.position, q(r.horse_name), q(r.former_name), q(r.breed), q(r.foaled), q(r.sex), q(r.sire), q(r.dam), q(r.dam_sire),
    q(r.breeder), q(r.dressage), q(r.show_jumping), q(r.cross_country), q(r.score), r.verified ? 1 : 0].join(', ')});`);
}

const MONTHS = { January: 1, February: 2, March: 3, April: 4, May: 5, June: 6, July: 7, August: 8, September: 9, October: 10, November: 11, December: 12 };
articles.forEach((a, i) => {
  const [d, m, y] = a.date.split(' ');
  const ts = `${y}-${String(MONTHS[m]).padStart(2, '0')}-${d.padStart(2, '0')} ${String(12 - i).padStart(2, '0')}:00:00`;
  out.push(`INSERT INTO news (title, body, snippet, image_key, published_at) VALUES (${q(a.title)}, ${q(a.full)}, ${q(a.snippet)}, NULL, '${ts}');`);
});

out.push(`INSERT INTO comments (scope, name, body, status, created_at) VALUES ('results', 'Sarah', 'Lovely to see a horse I bred placed again this week. Thank you for keeping the results going.', 'approved', '2026-04-06 10:00:00');`);
out.push(`INSERT INTO comments (scope, name, body, status, created_at) VALUES ('results', 'Tom', 'Great to have every result in one place, free to read.', 'approved', '2026-04-07 10:00:00');`);

writeFileSync(new URL('../seed/sample.sql', import.meta.url), out.join('\n') + '\n');
console.log(`seed/sample.sql: ${rows.length} placings, ${events.size} events, ${classes.size} classes, ${articles.length} news posts`);
