name: Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test
      - run: npx wrangler deploy --dry-run --env="" --outdir /tmp/worker-build
      - run: npm run build:ibsr
      - run: npx wrangler deploy --dry-run --env ibsr --outdir /tmp/worker-build-ibsr
